[package]
name = "libbuildpack"
version = "0.1.0"
authors = ["Terence Lee <hone02@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
log = "0.4"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
tempdir = "0.3"
